version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    volumes:
      - ./data-jaeger:/data
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: always
    networks:
      - my-network

networks:
  my-network:
    name: my-network